### ISSUE TITLE
Need a Reference Documentation..

### ISSUE THREAD

**Issue by SwiTool** [zaphoyd/websocketpp#538]
How should we know the methods if there is no reference ?
Same for parameters, content of classes, etc..

What I see is :
- unfinished tutorials on git
- unfinished documentation on website
- ridiculous "doc" on zaphoyd's website

So, it has been more than 2 years that this project began, and there are so many PR, could the author give admin access to some volunteer guy ?

**Comment by zaphoyd** [comment]
The most recent and comprehensive reference documentation is produced via running Doxygen on the bundled Doxyfile. I've been consolidating documentation here so that it gets properly versioned with the rest of the library, is available in one place and offline if needed.

As a convenience there is a mirror of this documentation build at http://docs.websocketpp.org/ That particular address has clearly not been well advertised. I've updated the readme to include it.

**Comment by SwiTool** [comment]
Wow, so many templates.
I'm still unable to find out how to git client IP from `connection_hdl`. Maybe you can help me on this ?

Thank you, you've done a great job here in this project.

**Comment by zaphoyd** [comment]
This discussion on the mailing list may be relevant:

https://groups.google.com/forum/#!searchin/websocketpp/ip$20address/websocketpp/b6Rmtj4SoF0/t5mbU4LM3fEJ
